---
# tasks file for dnswall
- name: "docker run dnswall-daemon container. "
  docker:
    name: dnswall-daemon
    image: coding4m/dnswall-daemon
    pull: always
    state: reloaded
    restart_policy: always
    ports:
    - "53:53/udp"
    - "53:53/tcp"
    volumes:
    - /etc/localtime:/etc/localtime
    command: -backend {{ backend }}


- name: "docker run dnswall-agent container. "
  docker:
    name: dnswall-agent
    image: coding4m/dnswall-agent
    pull: always
    state: reloaded
    restart_policy: always
    volumes:
    - /etc/localtime:/etc/localtime
    command: -backend {{ backend }} -docker-url {{ docker_url }}