---
# tasks file for dnswall

# ansible docker module pull image exists bug, use command pull instead

- name: "docker pull [dnswall-daemon, dnswall-agent] images."
  command: docker pull {{item}}
  with_items:
    - 'coding4m/dnswall-daemon'
    - 'coding4m/dnswall-agent'
  ignore_errors: true

- name: "docker run dnswall-daemon container. "
  docker:
    name: dnswall-daemon
    image: coding4m/dnswall-daemon
    pull: always
    state: reloaded
    restart_policy: always
    net: host
    env:
      DNSWALL_ADDR: "{{ docker_host }}:53"
      DNSWALL_BACKEND: "{{ etcd_cluster[:-1] }}/{{ dns_settings.path }}"
      DNSWALL_PATTERNS: "{{ dns_settings.patterns }}"
    volumes:
      - /etc/localtime:/etc/localtime:ro
#  notify:
#      - start firewalld
#      - allow dnswall-daemon traffics
#      - reload firewalld
#      - restart docker


- name: "docker run dnswall-agent container. "
  docker:
    name: dnswall-agent
    image: coding4m/dnswall-agent
    pull: always
    state: reloaded
    restart_policy: always
    net: host
    env:
      DNSWALL_BACKEND: "{{ etcd_cluster[:-1] }}/{{ dns_settings.path }}"
      DNSWALL_DOCKER_URL: "{{ docker_endpoint }}"
    volumes:
      - /etc/localtime:/etc/localtime:ro