---


- hosts: all
  user: root

  roles:
    - kernel

- hosts: etcd
  user: root

  roles:
    - etcd

- hosts: all
  user: root

  roles:
    - docker-engine

- hosts: all
  user: root

  roles:
    - docker-swarm
    - dnswall
    - proxywall
