---
- name: grub reset
  command: grub2-set-default 0

- name: reboot server
  shell: reboot
  async: 0
  poll: 0
  ignore_errors: true

- name: wait server
  local_action: wait_for host={{ansible_ssh_host | default(inventory_hostname) }} port={{ansible_ssh_port | default(22)}} delay=10
  sudo: false
