---

- name: stop firewalld
  service: name=firewalld state=stopped enabled=no sleep=5
  ignore_errors: true

- name: reload systemd
  command: systemctl daemon-reload
  ignore_errors: true

- name: restart docker
  service: name=docker state=restarted enabled=yes sleep=5
