---

- name: start firewalld
  service: name=firewalld state=started enabled=yes
  ignore_errors: true

- name: allow docker ifaces
  command: firewall-cmd --permanent --zone={{ docker_settings.expose_zone }} --change-interface={{ item }}
  with_items:
    - docker0
    - "{{ docker_settings.expose_iface }}"
  ignore_errors: true

- name: allow docker traffics
  firewalld: immediate=yes zone={{ docker_settings.expose_zone }} port={{ item }}/tcp permanent=yes state=enabled
  with_items:
    - "{{ docker_settings.expose_port }}"
  ignore_errors: true

- name: allow docker overlay traffics
  firewalld: immediate=yes zone={{ docker_settings.expose_zone }} source={{ item.source }} port={{ item.port }}/{{ item.proto }} permanent=yes state=enabled
  with_items:
    - { source: "{{docker_iface_network}}/{{docker_iface_netmask}}", port: 4789, proto: 'udp'}
    - { source: "{{docker_iface_network}}/{{docker_iface_netmask}}", port: 7946, proto: 'udp'}
    - { source: "{{docker_iface_network}}/{{docker_iface_netmask}}", port: 7946, proto: 'tcp'}
  ignore_errors: true

- name: reload firewalld
  command: firewall-cmd --reload

- name: reload systemd
  command: systemctl daemon-reload
  ignore_errors: true

- name: restart docker
  service: name=docker state=restarted enabled=yes sleep=5
