---
- name: "import rpm-gpg-key"
  rpm_key: key={{ elrepo_gpg_key }} state=present

- name: "install elrepo rpm"
  yum: name={{ elrepo_rpm }} state=present

- name: "upgrade kernel"
  yum: >
      name={{ item }}
      enablerepo=elrepo-kernel
      state=present
  with_items:
    - kernel-ml-devel
    - kernel-ml
  notify:
      - grub reset
      - reboot server
      - wait server
