---
# handlers file for etcd

- name: stop firewalld
  service: name=firewalld state=stopped enabled=no sleep=5
  ignore_errors: true

- name: reload systemd
  command: systemctl daemon-reload

- name: restart etcd
  service: name=etcd state=restarted enabled=yes sleep=5
