---
# handlers file for etcd

- name: start firewalld
  service: name=firewalld state=started enabled=yes
  ignore_errors: true

- name: allow etcd ifaces
  command: firewall-cmd --permanent --zone={{ item.zone }} --change-interface={{ item.iface }}
  with_items:
    - {zone: "{{etcd_settings.peer_zone}}", iface: "{{ etcd_settings.peer_iface }}"}
    - {zone: "{{etcd_settings.client_zone}}", iface: "{{ etcd_settings.client_iface }}"}

- name: allow etcd traffics
  firewalld: immediate=yes zone={{ item.zone }} source={{item.source}} port={{ item.port }}/tcp permanent=true state=enabled
  with_items:
    - {source : "{{etcd_peer_network}}/{{etcd_peer_netmask}}", zone: "{{etcd_settings.peer_zone}}", port : "{{etcd_settings.peer_port}}"}
    - {source : "{{etcd_client_network}}/{{etcd_client_netmask}}", zone: "{{etcd_settings.client_zone}}", port : "{{etcd_settings.client_port}}"}

- name: reload firewalld
  command: firewall-cmd --reload

- name: reload systemd
  command: systemctl daemon-reload

- name: restart etcd
  service: name=etcd state=restarted enabled=yes sleep=5
