---

# ansible docker module pull image exists bug, use command pull instead

- name: "docker run swarm-agent container."
  docker:
    name: swarm-agent
    image: swarm:latest
    pull: always
    state: reloaded
    restart_policy: always
    volumes:
    - /etc/localtime:/etc/localtime:ro
    command: join --addr {{swarm_advertise_addr}} {{swarm_cluster}}
