---
# tasks file for docker-swarm-manager

- name: "initial docker networks[overlay0, overlay-apps]."
  command: docker network create -d overlay {{item}}
  with_items:
    - 'overlay0'
    - 'overlay-apps'
  ignore_errors: true

# ansible docker module pull image exists bug, use command pull instead

- name: "docker run swarm-master container. "
  docker:
    name: swarm-master
    image: swarm:latest
    state: reloaded
    restart_policy: always
    ports:
    - "{{swarm_host}}:{{swarm_settings.expose_port}}:2375"
    volumes:
    - /etc/localtime:/etc/localtime:ro
    command: manage --addr {{swarm_host}}:{{swarm_settings.expose_port}} {{swarm_cluster}}
  notify:
    - start firewalld
    - allow swarm-master traffics
    - reload firewalld
    - restart docker