---
# tasks file for docker-swarm-manager

- name: "initial docker networks[overlay0, overlay-apps]."
  command: docker network create -d overlay {{item}}
  with_items:
    - 'overlay0'
    - 'overlay-apps'
  ignore_errors: true

# ansible docker module pull image exists bug, use command pull instead

- name: "docker run swarm-master container. "
  docker:
    name: swarm-master
    image: swarm:latest
#    pull: always
    state: reloaded
    restart_policy: always
    ports:
    - "{{swarm_host}}:{{swarm_port}}:2375"
    volumes:
    - /etc/localtime:/etc/localtime:ro
    command: manage --addr {{swarm_addr}} {{swarm_cluster}}
  notify:
    - start firewalld
    - allow swarm-master traffics
    - reload firewalld
    - restart docker

#- name: "docker run rethinkdb container. "
#  docker:
#    name: shipyard-rethinkdb
#    image: rethinkdb:latest
#    pull: always
#    state: reloaded
#    restart_policy: always
#    volumes:
#    - /etc/localtime:/etc/localtime
#
#- name: "docker run shipyard container. "
#  docker:
#    name: shipyard-controller
#    image: shipyard/shipyard:latest
#    pull: always
#    state: reloaded
#    restart_policy: always
#    links:
#    - "swarm-master:swarm"
#    - "shipyard-rethinkdb:rethinkdb"
#    ports:
#    - "{{swarm_admin_port}}:8080"
#    env:
#      VHOST: boss.workplus.io
#      VPORT: "8080"
#    volumes:
#    - /etc/localtime:/etc/localtime
#    command: -D server -d tcp://swarm:2375