---

etcd_cluster: "etcd://{% for host in groups['etcd'] %}{{ '%s:%s,'|format(hostvars[host]['ansible_' + hostvars[host]['etcd_settings']['client_iface']]['ipv4']['address'], hostvars[host]['etcd_settings']['client_port'] ) }}{% endfor %}"

swarm_host: "{{ hostvars[inventory_hostname]['ansible_' + docker_settings.expose_iface]['ipv4']['address'] }}"
swarm_advertise_addr: "{{ swarm_host }}:{{docker_settings.expose_port}}"
swarm_cluster: "{{etcd_cluster[:-1]}}"
