---
# defaults file for etcd
etcd_version: v2.2.5

etcd_peer_network: "{{ hostvars[inventory_hostname]['ansible_' + etcd_settings.peer_iface]['ipv4']['network'] }}"
etcd_peer_netmask: "{{ hostvars[inventory_hostname]['ansible_' + etcd_settings.peer_iface]['ipv4']['netmask'] | ipaddr('prefix') }}"
etcd_advertise_peer_addr: "{{ hostvars[inventory_hostname]['ansible_' + etcd_settings.peer_iface]['ipv4']['address'] }}:{{ etcd_settings.peer_port }}"
etcd_advertise_peer_urls: "{{ etcd_settings.peer_proto }}://{{ etcd_advertise_peer_addr }}"

etcd_client_network: "{{ hostvars[inventory_hostname]['ansible_' + etcd_settings.client_iface]['ipv4']['network'] }}"
etcd_client_netmask: "{{ hostvars[inventory_hostname]['ansible_' + etcd_settings.client_iface]['ipv4']['netmask'] | ipaddr('prefix') }}"
etcd_advertise_client_addr: "{{ hostvars[inventory_hostname]['ansible_' + etcd_settings.client_iface]['ipv4']['address'] }}:{{ etcd_settings.client_port }}"
etcd_advertise_client_urls: "{{ etcd_settings.client_proto }}://{{ etcd_advertise_client_addr }}"

cluster_addr: "{% for host in groups['etcd'] %}{{ '%s=%s://%s:%s,'|format(host, hostvars[host]['etcd_settings']['peer_proto'], hostvars[host]['ansible_' + hostvars[host]['etcd_settings']['peer_iface']]['ipv4']['address'], hostvars[host]['etcd_settings']['peer_port'] ) }}{% endfor %}"
cluster_token: etcd-cluster
cluster_state: new