---
# tasks file for proxywall

# ansible docker module pull image exists bug, use command pull instead

- name: "docker pull [proxywall-agent, proxywall-daemon] images."
  command: docker pull {{item}}
  with_items:
    - 'coding4m/proxywall-agent'
    - 'coding4m/proxywall-daemon'
  ignore_errors: true

- name: "docker run proxywall-agent container. "
  docker:
    name: proxywall-agent
    image: coding4m/proxywall-agent
#    pull: always
    state: reloaded
    restart_policy: always
    net: host
    env:
      PROXYWALL_BACKEND: "{{ etcd_cluster[:-1] }}/{{ proxywall_path }}"
      PROXYWALL_DOCKER_URL: "{{ docker_url }}"
    volumes:
      - /etc/localtime:/etc/localtime:ro