---
# tasks file for proxywall

# ansible docker module pull image exists bug, use command pull instead

- name: "docker pull [proxywall-agent] images."
  command: docker pull {{item}}
  with_items:
    - 'coding4m/proxywall-agent'
  ignore_errors: true

- name: "docker run proxywall-agent container. "
  docker:
    name: proxywall-agent
    image: coding4m/proxywall-agent
#    pull: always
    state: reloaded
    restart_policy: always
    net: host
    volumes:
    - /etc/localtime:/etc/localtime
    command: -backend {{ backend_ops }} -docker-url {{ docker_url }}